"""Extraction against realistic synthetic documents.

These use the fixtures in tests/fixtures/, generated by tools/make_fixtures.py.
Everything there is fabricated and stamped SPECIMEN - no real veteran's record
is committed to this repository or sent to an API.

The interesting case is dd214_scanned.jpg: rotated, greyscale, speckled and
JPEG-compressed, because that is what a veteran actually uploads.
"""

from pathlib import Path

import pytest

from src import extract, gemini
from src.gemini import Attachment

FIXTURES = Path(__file__).parent / "fixtures"

EXPECTED_DD214 = {
    "first_name": "Marcus",
    "last_name": "Rivera",
    "dob": "1990-07-22",
    "service_start": "2009-09-14",
    "service_end": "2016-11-03",
    "branch": "army",
    "discharge_type": "honorable",
}

live = pytest.mark.skipif(not gemini.available(), reason="no GEMINI_API_KEY configured")
needs_fixtures = pytest.mark.skipif(
    not (FIXTURES / "dd214_scanned.jpg").exists(),
    reason="fixtures not generated; run python tools/make_fixtures.py",
)


def load(name: str) -> Attachment:
    return Attachment(name, (FIXTURES / name).read_bytes())


def test_fixtures_are_marked_as_synthetic():
    """A committed document must never look like a real veteran's record."""
    text = (FIXTURES / "dd214.txt").read_text()
    assert "SPECIMEN" in text
    assert "000-00-0000" in text        # never issued as a real SSN


@needs_fixtures
@live
@pytest.mark.parametrize("filename", ["dd214_clean.png", "dd214_scanned.jpg"])
def test_dd214_identity_survives_a_bad_scan(filename):
    payload = extract.extract_from_document(load(filename))
    assert payload["document_type"] == "dd214"

    fields = {key: str(value) for key, value in
              extract.veteran_fields_from(payload).items()}
    for key, expected in EXPECTED_DD214.items():
        assert fields.get(key) == expected, f"{filename}: {key} was {fields.get(key)}"


@needs_fixtures
@live
def test_medical_record_yields_conditions_with_onset_dates():
    payload = extract.extract_from_document(load("medical_record.png"))
    assert payload["document_type"] == "medical_record"

    conditions = extract.conditions_from(payload)
    names = " ".join(condition["name"].lower() for condition in conditions)
    assert "tinnitus" in names
    assert "lumbar" in names or "back" in names

    # "present since 2011" has to become a date; onset drives the claim.
    dated = [c for c in conditions if c["onset_date"]]
    assert dated, "no onset date was extracted from phrases like 'since 2011'"
    assert any(c["onset_date"].year in (2011, 2012) for c in dated)


@needs_fixtures
@live
def test_decision_letter_supplies_the_date_that_starts_the_clocks():
    from datetime import date

    payload = extract.extract_from_document(load("decision_letter.png"))
    assert payload["document_type"] == "decision_letter"
    assert extract.parse_date(payload["decision_date"]) == date(2026, 6, 4)


@needs_fixtures
@live
def test_a_scanned_decision_letter_routes_the_claim_into_lane_five():
    """The end-to-end point: one upload should set the lane and its deadlines."""
    from src import intake_chat, lanes

    session = intake_chat.new_session()
    session.story_done = True
    intake_chat.apply_document(session, load("decision_letter.png"))

    context = session.claim.context
    assert context.disagrees_with_decision
    assert context.decision_date is not None
    assert lanes.determine_lane(context) == lanes.Lane.DECISION_REVIEW
    assert any("Board Appeal" in deadline.label for deadline in lanes.deadlines(session.claim))
