"""Extraction against realistic synthetic documents.

These use the fixtures in tests/fixtures/, generated by tools/make_fixtures.py.
Everything there is fabricated and stamped SPECIMEN - no real veteran's record
is committed to this repository or sent to an API.

The interesting case is dd214_scanned.jpg: rotated, greyscale, speckled and
JPEG-compressed, because that is what a veteran actually uploads.
"""

from pathlib import Path

import pytest

from src import extract, gemini
from src.gemini import Attachment

FIXTURES = Path(__file__).parent / "fixtures"

EXPECTED_DD214 = {
    "first_name": "Marcus",
    "last_name": "Rivera",
    "dob": "1990-07-22",
    "service_start": "2009-09-14",
    "service_end": "2016-11-03",
    "branch": "army",
    "discharge_type": "honorable",
}

live = pytest.mark.skipif(not gemini.available(), reason="no GEMINI_API_KEY configured")
needs_fixtures = pytest.mark.skipif(
    not (FIXTURES / "dd214_scanned.jpg").exists(),
    reason="fixtures not generated; run python tools/make_fixtures.py",
)


def load(name: str) -> Attachment:
    return Attachment(name, (FIXTURES / name).read_bytes())


def test_fixtures_are_marked_as_synthetic():
    """A committed document must never look like a real veteran's record."""
    text = (FIXTURES / "dd214.txt").read_text()
    assert "SPECIMEN" in text
    assert "000-00-0000" in text        # never issued as a real SSN


@needs_fixtures
@live
@pytest.mark.parametrize("filename", ["dd214_clean.png", "dd214_scanned.jpg"])
def test_dd214_identity_survives_a_bad_scan(filename):
    payload = extract.extract_from_document(load(filename))
    assert payload["document_type"] == "dd214"

    fields = {key: str(value) for key, value in
              extract.veteran_fields_from(payload).items()}
    for key, expected in EXPECTED_DD214.items():
        assert fields.get(key) == expected, f"{filename}: {key} was {fields.get(key)}"


@needs_fixtures
@live
def test_medical_record_yields_conditions_with_onset_dates():
    payload = extract.extract_from_document(load("medical_record.png"))
    assert payload["document_type"] == "medical_record"

    conditions = extract.conditions_from(payload)
    names = " ".join(condition["name"].lower() for condition in conditions)
    assert "tinnitus" in names
    assert "lumbar" in names or "back" in names

    # "present since 2011" has to become a date; onset drives the claim.
    dated = [c for c in conditions if c["onset_date"]]
    assert dated, "no onset date was extracted from phrases like 'since 2011'"
    assert any(c["onset_date"].year in (2011, 2012) for c in dated)


@needs_fixtures
@live
def test_decision_letter_supplies_the_date_that_starts_the_clocks():
    from datetime import date

    payload = extract.extract_from_document(load("decision_letter.png"))
    assert payload["document_type"] == "decision_letter"
    assert extract.parse_date(payload["decision_date"]) == date(2026, 6, 4)


@needs_fixtures
@live
@pytest.mark.parametrize("filename,expected", [
    ("dd214_scanned.pdf", "dd214"),
    ("separation_orders.pdf", "separation_orders"),
    ("service_treatment_record.pdf", "service_treatment_record"),
    ("medical_record.pdf", "medical_record"),
    ("audiology_report.pdf", "audiology_report"),
    ("nexus_letter.pdf", "nexus_letter"),
    ("buddy_statement.pdf", "buddy_statement"),
    ("decision_letter.pdf", "decision_letter"),
])
def test_every_demo_document_is_classified_correctly(filename, expected):
    """A misclassified fixture is a broken demo, so all of them are checked."""
    assert extract.extract_from_document(load(filename))["document_type"] == expected


@needs_fixtures
@live
def test_separation_orders_put_the_claim_in_the_bdd_lane():
    """The Lane 1 path: no DD-214 yet, so the orders supply the separation date."""
    from src import intake_chat, lanes

    session = intake_chat.new_session()
    session.story_done = True
    intake_chat.apply_document(session, load("separation_orders.pdf"))

    context = session.claim.context
    assert context.still_serving
    assert context.separation_date is not None
    assert context.separation_date > __import__("datetime").date.today()
    assert lanes.determine_lane(context) == lanes.Lane.BDD
    assert any("BDD window" in deadline.label for deadline in lanes.deadlines(session.claim))


@needs_fixtures
@live
def test_the_audiogram_closes_the_hearing_test_checklist_item():
    from src import evidence_rules, intake_chat

    session = intake_chat.new_session()
    session.story_done = True
    intake_chat.ClaimIntake(session.claim).add_condition(
        name="Tinnitus", current_symptoms="Constant ringing in both ears.",
        started_in_service=True)
    before = [i.label for i in evidence_rules.missing_evidence(session.claim)]
    assert any("Audiology" in label for label in before)

    intake_chat.apply_document(session, load("audiology_report.pdf"))
    after = [i.label for i in evidence_rules.missing_evidence(session.claim)]
    assert not any("Audiology" in label for label in after)


@needs_fixtures
@live
def test_a_scanned_decision_letter_routes_the_claim_into_lane_five():
    """The end-to-end point: one upload should set the lane and its deadlines."""
    from src import intake_chat, lanes

    session = intake_chat.new_session()
    session.story_done = True
    intake_chat.apply_document(session, load("decision_letter.png"))

    context = session.claim.context
    assert context.disagrees_with_decision
    assert context.decision_date is not None
    assert lanes.determine_lane(context) == lanes.Lane.DECISION_REVIEW
    assert any("Board Appeal" in deadline.label for deadline in lanes.deadlines(session.claim))
